/opt/slurm/bin/sbatch scripts/Llama-2-70b-hf-num-shots-0NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-hf-num-shots-1NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-hf-num-shots-2NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-hf-num-shots-3NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-hf-num-shots-4NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-hf-num-shots-5NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-hf-num-shots-6NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-hf-num-shots-7NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-hf-num-shots-8NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-hf-num-shots-9NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-hf-num-shots-10NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-0NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-1NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-2NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-3NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-4NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-5NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-6NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-7NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-8NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-9NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-10NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-0NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-1NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-2NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-3NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-4NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-5NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-6NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-7NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-8NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-9NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-10NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-0NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-1NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-2NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-3NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-4NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-5NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-6NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-7NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-8NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-9NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-10NEW-LARGE-MODEL-iclNEW-LARGE-MODEL.sh
