/usr/bin/sbatch scripts/Llama-2-70b-hf-num-shots-0-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-hf-num-shots-1-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-hf-num-shots-2-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-hf-num-shots-3-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-hf-num-shots-4-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-hf-num-shots-5-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-hf-num-shots-6-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-hf-num-shots-7-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-hf-num-shots-8-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-hf-num-shots-9-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-hf-num-shots-10-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-0-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-1-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-2-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-3-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-4-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-5-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-6-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-7-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-8-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-9-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Llama-2-70b-chat-hf-num-shots-10-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-0-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-1-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-2-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-3-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-4-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-5-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-6-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-7-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-8-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-9-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-num-shots-10-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-0-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-1-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-2-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-3-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-4-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-5-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-6-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-7-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-8-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-9-iclLARGE-MODEL.sh
/usr/bin/sbatch scripts/Meta-Llama-3-70B-Instruct-num-shots-10-iclLARGE-MODEL.sh
