/opt/slurm/bin/sbatch scripts/Llama-2-7b-hf-num-shots-0NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-hf-num-shots-1NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-hf-num-shots-2NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-hf-num-shots-3NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-hf-num-shots-4NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-hf-num-shots-5NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-hf-num-shots-6NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-hf-num-shots-7NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-hf-num-shots-8NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-hf-num-shots-9NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-hf-num-shots-10NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-chat-hf-num-shots-0NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-chat-hf-num-shots-1NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-chat-hf-num-shots-2NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-chat-hf-num-shots-3NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-chat-hf-num-shots-4NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-chat-hf-num-shots-5NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-chat-hf-num-shots-6NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-chat-hf-num-shots-7NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-chat-hf-num-shots-8NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-chat-hf-num-shots-9NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Llama-2-7b-chat-hf-num-shots-10NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-num-shots-0NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-num-shots-1NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-num-shots-2NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-num-shots-3NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-num-shots-4NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-num-shots-5NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-num-shots-6NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-num-shots-7NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-num-shots-8NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-num-shots-9NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-num-shots-10NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-0NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-1NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-2NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-3NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-4NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-5NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-6NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-7NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-8NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-9NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
/opt/slurm/bin/sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-10NEW-SMALL-MODEL-iclNEW-SMALL-MODEL.sh
