sbatch scripts/Llama-2-7b-hf-num-shots-0-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-hf-num-shots-1-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-hf-num-shots-2-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-hf-num-shots-3-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-hf-num-shots-4-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-hf-num-shots-5-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-hf-num-shots-6-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-hf-num-shots-7-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-hf-num-shots-8-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-hf-num-shots-9-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-hf-num-shots-10-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-chat-hf-num-shots-0-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-chat-hf-num-shots-1-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-chat-hf-num-shots-2-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-chat-hf-num-shots-3-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-chat-hf-num-shots-4-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-chat-hf-num-shots-5-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-chat-hf-num-shots-6-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-chat-hf-num-shots-7-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-chat-hf-num-shots-8-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-chat-hf-num-shots-9-iclSMALL-MODEL.sh
sbatch scripts/Llama-2-7b-chat-hf-num-shots-10-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-num-shots-0-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-num-shots-1-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-num-shots-2-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-num-shots-3-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-num-shots-4-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-num-shots-5-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-num-shots-6-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-num-shots-7-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-num-shots-8-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-num-shots-9-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-num-shots-10-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-0-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-1-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-2-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-3-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-4-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-5-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-6-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-7-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-8-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-9-iclSMALL-MODEL.sh
sbatch scripts/Meta-Llama-3-8B-Instruct-num-shots-10-iclSMALL-MODEL.sh
